### ISSUE TITLE
Headsup : I needed to alter filebrowser config in arrcompose.yaml

### ISSUE THREAD

**Issue by johnkattenhorn** [TechHutTV/homelab#18]
I think new versions of the filebrowser container needs a different docker-compose settings; I had to alter mine from this:

```
filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    volumes:
      - /data:/srv # Directory you want exposed to filebrowser.
      - /docker/filebrowser/filebrowser.db:/database/filebrowser.db
      - /docker/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.7
    restart: unless-stopped
```

to this:

```
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    volumes:
      - /data:/srv # Directory you want exposed to filebrowser.
      - /docker/filebrowser/data:/data
      - /docker/filebrowser/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.7
    restart: unless-stopped
```
