### ISSUE TITLE
Qbittorrent download path in *arr docker stack points to a non-writeable path

### ISSUE THREAD

**Issue by hsu10405** [TechHutTV/homelab#28]
I noticed that the Qbittorrent section in arr stack docker compose file points to the following download path.

https://github.com/TechHutTV/homelab/blob/340e4ce4248a5e938cba52afae41f3aeba6ee971/media/compose.yaml#L67 

Linuxserver.io by default points all incoming download to `/downloads`. The declaration above would throw a `permission denied` error whenever you start downloading. You would only notice it when inspecting the log in `./qbittorrent` folder, docker container log will not show anything. It's not the end of the world though as you can change the path in the Qbittorrent WebUI to `/data` and move errored torrents manually to new path.

![Image](https://github.com/user-attachments/assets/94c7e7bd-84e3-4ae4-aace-0bdab42cc9de)

But I would rather move this declaration to the docker compose file to keep things simple and aligned to linuxserver.io's guide.

```yaml
    volumes:
      - ./qbittorrent:/config
      - /data:/downloads
```

**Comment by TechHutTV** [comment]
Hey ther @hsu10405, I use `/data:/data` across everything. If you're running qbittorrent with the same permissions as the owner of the directories (ie. 1000:1000) you shouldn't have any permissions issues. 

```
  qbittorrent:
...
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
...
    volumes:
      - ./qbittorrent:/config
      - /data:/data
...
```

__For the save paths in the WebUI I set it to the following:__

Default Save Path: `/data/downloads/qbittorrent/completed`
Keep incomplete torrents in: `/data/downloads/qbittorrent/incomplete`
Copy .torrent files to: `/data/downloads/qbittorrent/torrents`
