### ISSUE TITLE
qBittorrent won't download

### ISSUE THREAD

**Issue by Akorian** [TechHutTV/homelab#38]
Hi, I just used the docker-compose template with the .env to up my own arr stack. I use windscribe as my VPN and connected it to gluetun. Running the test command results in a working connection as far as I can see.
```
OK: 10 MiB in 19 packages
{
  "ip": "xx.xx.xx.xx",
  "hostname": "ip-xx-xx.windscribe.com",
  "city": "Jakarta",
  "region": "Jakarta",
  "country": "ID",
  "loc": "-6.2510,106.8665",
  "org": "AS150249 PT Atharva Telematika Persada",
  "postal": "13630",
  "timezone": "Asia/Jakarta",
  "readme": "https://ipinfo.io/missingauth"
}
```

I entered qbittorrent, checked the option to use only **tun0**, changed the web-password, updated the download links and added a .torrentfile of ubuntu and one of fedora to test connectivity. The ubuntu one shows name, size, seeds and peers while the fedora one doesn't. Ubuntu  was marked as errored after some time while fedora only stalls. 
Since I dont have any required port forwarding by windscribe, I have not set anything of that up and the `TORRENTING_PORT` is just the port I chose for the wireguard connection during the connection setup process in the windscribe interface **1194**. Since that didnt work, I also tried the port **6881** and some random ports.

<details><summary>docker-compose.yml</summary>
<p>

```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun # If running on an LXC see readme for more info.
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.2
    ports:
      - 1194:1194 # windscribe wireguard port I chose
      - 8080:8080 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port
      - 6789:6789 # nzbget
      - 9696:9696 # prowlarr
    volumes:
      - /opt/docker/volumes/gluetun:/gluetun
    # Make a '.env' file in the same directory.
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080 # must match "qbittorrent web interface" port number in gluetun's service above
      - TORRENTING_PORT=6881
    volumes:
      - /opt/docker/volumes/qbittorrent-config:/config
      - /mnt/media/:/media
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  # See the 'qBittorrent Stalls with VPN Timeout' section for more information.
  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/volumes/nzbget-config:/config
      - /mnt/media:/media
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/volumes/prowlarr-config:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/volumes/sonarr-config:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.3

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/volumes/radarr-config:/config
      - /mnt/media:/media
    ports:
      - 7878:7878
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.4

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/volumes/lidarr-config:/config
      - /mnt/media:/media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8686:8686
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.5

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/volumes/bazarr-config:/config
      - /mnt/media:/media
    ports:
      - 6767:6767
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.6

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/volumes/jellyseerr-config:/app/config
    ports:
      - 5055:5055
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.9
    restart: unless-stopped


networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.39.0.0/24
```

</p>
</details> 

<details><summary>.env</summary>
<p>

```
# General UID/GIU and Timezone
TZ=Europe/Moscow
PUID=1000
PGID=1000

# Input your VPN provider and type here
VPN_SERVICE_PROVIDER=windscribe
VPN_TYPE=wireguard

# Copy all these varibles from your generated configuration file
WIREGUARD_PUBLIC_KEY=<value of "PublicKey" in wireguard.conf>
WIREGUARD_PRIVATE_KEY=<value of "PrivateKey" in wireguard.conf>
WIREGUARD_PRESHARED_KEY=<value of "PresharedKey" in wireguard.conf>
WIREGUARD_ADDRESSES=<value of "Address" in wireguard.conf (including /32 if not included, wont start)>
WIREGUARD_ENDPOINT_PORT=<only port value of "Endpoint" in wireguard.conf>
SERVER_REGIONS=Indonesia

# Heath check duration
HEALTH_VPN_DURATION_INITIAL=120s

```

</p>
</details> 

I don't know how I can proceed since neither the qbittorrent container nor gluetun produce any error logs. So if anyone has an Idea what can be wrong, please lemme know.
