### ISSUE TITLE
Issue in "arr-compose.yaml" regarding qbittorrent's deunhealth monitoring 

### ISSUE THREAD

**Issue by delro92** [TechHutTV/homelab#8]
When replicating your setup on my machine, I had to use 

- deunhealth.restart.on.unhealthy=true
instead of 
- deunhealth.restart.on.unhealthy= "true"

```
# Healthcheck was added to work with deunhealth to restart container
# on unhealthy status. labels allows deunhealth to monitor.
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true #without space or quotes
``` 
After doing that my deunhealth logs show:
2025-01-06T18:33:12+01:00 INFO Monitoring new container c74a22cf6c48_qbittorrent to restart when becoming unhealthy

which previously didn't. 

Here is the line I am talking about:
https://github.com/TechHutTV/homelab/blob/8747d5283a407171ca3adfc5b0b32d0557b44c55/media/arr-compose.yaml#L60

Love your videos, keep it up!
